
depthpriceclient:
  wsc:
    scheme: wss
    host: engine2.kryptono.exchange
    path: /ws/v1/dp/BTC_USDT

historytradeclient:
  wsc:
    scheme: wss
    host: engine2.kryptono.exchange
    path: /ws/v1/ht/BTC_USDT

candlesticksclient:
  wsc:
    scheme: wss
    host: engine2.kryptono.exchange
    path: /ws/v1/cs/BTC_USDT@1m

ticker24hclient:
  wsc:
    scheme: wss
    host: engine2.kryptono.exchange
    path: /ws/v1/tk

cerberusclient:
  wsc:
    scheme: wss
    host: engine2.kryptono.exchange
    path: /ws/v1/cr/BTC_USDT

reloadsymbolclient:
  wsc:
    scheme: ws
    host: 127.0.0.1:15401
    path: /dataws/reloadsymbol
