
market:
  listpair: ETH_USDT;BTC_USDT

depthprice:
  wss:
    host: 0.0.0.0
    port: 15501

historytrade:
  wss:
    host: 0.0.0.0
    port: 15701

candlesticks:
  wss:
    host: 0.0.0.0
    port: 15601

ticker24h:
  wss:
    host: 0.0.0.0
    port: 15801

cerberus:
  wss:
    host: 0.0.0.0
    port: 18001


webserver:
  host: 0.0.0.0
  port: 15901

dataws:
  host: 127.0.0.1
  port: 15401
